[package]
name = "wisard_rusty"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rusty_wisard"
path = "src/api_test.rs"

[[bin]]
name = "mnist_test"
path = "src/mnist_test.rs"

[workspace]
members = ["dict_wisard", "rocket_wisard"]

[dependencies]
rocket_wisard = { path = "rocket_wisard" }
dict_wisard = { path = "dict_wisard" }
