[package]
name = "wisard_rusty"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libwisard"
path = "src/lib/lib.rs"

[[bin]]
name = "test_lib"
path = "src/bin/test_lib/main.rs"

[[bin]]
name = "front"
path = "src/bin/front/main.rs"

[[bin]]
name = "worker"
path = "src/bin/worker/main.rs"

[dependencies]
rand = "0.8.4"
byteorder = "1.4.3"
ndarray = "0.15.3"
flate2 = "1.0.20"
rayon = "1.5.1"
image = "0.23.14"
serde = "1.0.126"
rocket = "0.4.10"
kube = "0.58.1"
kube-runtime = "0.58.1"
k8s-openapi = { version = "0.12.0", default-features = false, features = [
    "v1_20",
] }
