[package]
name = "rusty-wisard"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rocket_wisard_test"
path = "src/rocket_test.rs"

[[bin]]
name = "dict_wisard_test"
path = "src/dict_test.rs"

[[bin]]
name = "actix_wisard_test"
path = "src/actix_test.rs"

[lib]
name = "dataloaders"
path = "lib/dataloaders.rs"

[workspace]
members = ["wisard", "rocket_wisard", "actix_wisard"]

[dependencies]
actix-wisard = { path = "actix_wisard" }
rocket-wisard = { path = "rocket_wisard" }
wisard = { path = "wisard" }
flate2 = "1.0.20"
byteorder = "1.4.3"
